spring:
  application:
    name: identity-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8095

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


