spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
  config:
    import: "configserver:http://localhost:8888/"