spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energytoolrent
    driver-class-name: org.postgresql.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect