spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e2rent
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    web: warn