package com.e2rent.equipment.enums;

public enum EquipmentSubcategory {
    // BACKUP_POWER
    DIESEL_GENERATOR,
    GAS_GENERATOR,
    INVERTER_GENERATOR,
    UPS,
    ENERGY_STORAGE,

    // RENEWABLE_ENERGY
    SOLAR_PANEL,
    WIND_TURBINE,
    SOLAR_INVERTER,
    CHARGE_CONTROLLER,

    // DISTRIBUTION
    DISTRIBUTION_BOX,
    CIRCUIT_BREAKER,
    PHASE_SWITCH,
    RELAY,

    // CABLING
    EXTENSION_CORD,
    CABLE_DRUM,
    ADAPTER,
    GROUNDING_EQUIPMENT,

    // INDUSTRIAL
    TRANSFORMER,
    VOLTAGE_STABILIZER,
    FREQUENCY_CONVERTER,
    ELECTRIC_COMPRESSOR,

    // TOOLS
    CHARGING_STATION,
    WELDING_MACHINE,
    DC_TO_AC_INVERTER,

    // MONITORING
    ENERGY_METER,
    SMART_SENSOR,
    SMART_HOME_DEVICE,

    // OTHER
    OTHER
}

